Poging tot jsf pagina's maken
javax.el.PropertyNotFoundException: The class 'model.service.IUserService$307824877$Proxy$_$$_Weld$EnterpriseProxy$' does not have the property 'Users'